### ISSUE TITLE
Flyway should automatically update if the version changes

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-flywaydb#15]
Flyway should automatically update if the version changes.  If flyway 3.2.1 is installed, flywaydb cookbook 5.1.0 should ensure that flyway 4.0 is installed.

**Comment by dhoer** [comment]
The remote_file create action should detect a change in the file and download it then fire off notifications:
`Default. Create a file. If a file already exists (but does not match), update that file to match.`

But that is not happening.  It could be because of the conditional statements wrapping the resources to be notified, or inline conditional statements on remote_file itself, or both.

**Comment by akrapfl** [comment]
Is the expectation that this cookbook will continue to pin to the latest flyway available at the time as it's released?

**Comment by dhoer** [comment]
Yes

**Comment by dhoer** [comment]
The issue was that all versions installed to the same directory. This has now changed to install to separate directories.  A symbolic link will point to the current version e.g., /opt/flyway -> /opt/flyway-3.2.1.
