### ISSUE TITLE
upgrade mariadb driver

### ISSUE THREAD

**Issue by akrapfl** [dhoer/chef-flywaydb#22]
Flyway is currently bundling a version of the mariadb driver that is known to have bugs.  Flyway has an open issue to fix it, but until that time, chef-flywaydb should upgrade the driver.

The proposed change is to check the version of the mariadb driver, and if the buggy version is present, remove it and download the newer version.  @dhoer knows the proper versions, as he's aware of this issue.  If the buggy version is not present, no action need be taken.

**Comment by dhoer** [comment]
https://github.com/flyway/flyway/issues/1319

**Comment by dhoer** [comment]
The plan is to allow a version to be set for the MariaDb with default nil.  If version is set, flywaydb will attempt to download and replace the current mariadb driver with it. This will allow a user to set an older or newer version of MariaDB outside of flywaydb package.

**Comment by akrapfl** [comment]
Can we have the default version be 1.4.4, and allow the user to specify nil or something else?  This is expected to be the next version used by the underlying flyway software anyway, so it would not be harmful.  Also, how will the user set an alternate value?  Via an attribute specified by the caller, or via a node attribute that can be overridden at any calling cookbook?  For example:

`default['flywaydb']['mariadb']['version'] = '1.4.4'`

**Comment by dhoer** [comment]
Since flyway is not very agile, I will just try to keep the mariadb version update and no longer be dependent on flyway's version of mariadb.
