### ISSUE TITLE
Do not create a user/group when passing in values

### ISSUE THREAD

**Issue by nickptrvc** [dhoer/chef-flywaydb#25]
Currently you must run as flyway or the specified user to execute flyway. Would it make sense to update the permission bits to allow anyone in the flyway group to execute this?

I looked into setting my own user, e.g. jenkins, but the install uses the `user` resource and sets a few other properties like shell and home which I don't want changed at all.

**Comment by dhoer** [comment]
So passing in jenkins user will cause flyway to modify it?  I didn't expect this.  I would want the user and group to do nothing if they already exist.  I think there is a way to do that.  Would that work for you?

**Comment by nickptrvc** [comment]
@dhoer 
Let me double check. I was just reading the code and assumed that is what it did.

**Comment by nickptrvc** [comment]
@dhoer 
Yes, it does look like its attempting to change the user's properties.

Error when jenkins is still running:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-c", "Flyway System User", "-s", "/sbin/nologin", "-d", "/opt/flyway-3.2.1", "jenkins"] ----
STDOUT: 
STDERR: usermod: user jenkins is currently used by process 1822
---- End output of ["usermod", "-c", "Flyway System User", "-s", "/sbin/nologin", "-d", "/opt/flyway-3.2.1", "jenkins"] ----
Ran ["usermod", "-c", "Flyway System User", "-s", "/sbin/nologin", "-d", "/opt/flyway-3.2.1", "jenkins"] returned 8
```

Shutdown jenkins, rerun recipe, and confirm that it changes the jenkins user properties:
```
cat /etc/passwd | grep jenkins
jenkins:x:2003:2003::/mnt/jenkins/home:/bin/bash

# run recipe and check jenkins user again

cat /etc/passwd | grep jenkins
jenkins:x:2003:2003:Flyway System User:/opt/flyway-3.2.1:/sbin/nologin
```

Chef Docs seem to confirm that it will update the user's properties:
> :create
Default. Create a user with given properties. If a user already exists (but does not match), update that user to match.

**Comment by dhoer** [comment]
Ok, I guess it will need a not_if guard added that supports both windows and linux.

**Comment by dhoer** [comment]
What do you think about changing the defaults of user and group to nil?  If nil, then create flyway user and/or group, otherwise; assume user and/or group passed in already exists so don't create the user and/or group.

**Comment by dhoer** [comment]
Or maybe add not_if guard as originally planned. I will have to see if the following works:

`not_if { node['etc']['passwd'][new_resource.user]`

Not sure how windows platform would handle this...

**Comment by nickptrvc** [comment]
I think having a default user/group of nil would work. I thought about using node['etc']['passwd'][new_resource.user] too, but came to the same conclusion. 

I also thought about a helper method or special resource that can load and detect users, but I feel that may be overkill for this situation.
