### ISSUE TITLE
On using the sensitive attribute

### ISSUE THREAD

**Issue by cheeseplus** [dhoer/chef-flywaydb#3]
Given our discussion in IRC:

1. If I have `attribute :sensitive, default: true` on my resource
2. And the user does `my_resource 'hi' do; puts sensitive; end`
3. I expect it to print `true` (edited)

In the current Chef, it prints `false`

To resolve this you'll want to have the below in the resource:

```
def initialize(*args)
  super
  @sensitive = true
end
```

The reason that this returns an unexpected value is that the common property `sensitive` has a default value and because of how the initialization process works, if you're getting the default value for the common `sensitive` not the default you set. The line below is where the trouble originates from:

https://github.com/chef/chef/blob/master/lib/chef/resource.rb#L161

For the interim: 
- if you'd like to use the name `sensitive` you could use the above fix to basically override that default
- use another name as discussed
- I haven't opened an issue yet but discussed with @jkeiser removing the default initialization or making it safer for cases just like this.

Cheers!

(feel free to close the issue, just wanted to follow up since we nailed this down)

**Comment by dhoer** [comment]
Thanks for this!  I will discuss with the team what approach we should take.

**Comment by dhoer** [comment]
This cookbook has had 2 major revs to the version due to security fixes already, so sensitive will be patched at this time.
