### ISSUE TITLE
unable to autodetect JDBC driver

### ISSUE THREAD

**Issue by faizan80** [dhoer/chef-flywaydb#32]
Hi,
I am getting this error: 
RuntimeError: ERROR: Unable to autodetect JDBC driver for url: jdbc:mysql/127.0.0.1/mydb

There is this list of drivers:
ll /opt/flywaydb/flyway/drivers/
total 11868
-rw-r--r-- 1 flyway flyway 3224708 Feb 23  2016 derby-10.12.1.1.jar
-rw-r--r-- 1 flyway flyway  590087 Feb 23  2016 derbyclient-10.12.1.1.jar
-rw-r--r-- 1 flyway flyway 1791969 Feb  1 14:34 h2-1.4.193.jar
-rw-r--r-- 1 flyway flyway 1515894 Oct 18 20:54 hsqldb-2.3.4.jar
-rw-r--r-- 1 flyway flyway  317816 Apr 14  2014 jtds-1.3.1.jar
-rw-r--r-- 1 flyway flyway  371700 May 26  2016 mariadb-java-client-1.4.5.jar
-rw-r--r-- 1 flyway flyway  644836 Feb 23  2016 postgresql-9.4.1208.jre6.jar
-rw-r--r-- 1 flyway flyway       0 Feb 16 18:00 put-your-jdbc-drivers-here.txt
-rw-r--r-- 1 flyway flyway 3677896 Aug  3  2014 sqlite-jdbc-3.7.15-M1.jar

The conf file looks like: 
flyway.mysql_driver=true
flyway.url=jdbc:mysql/127.0.0.1/db
flyway.user=root
flyway.password={somepassword}
flyway.locations=filesystem:/tmp//c360-database/sql
flyway.cleanDisabled=true

I thought mysql_driver=true, should install the driver ? or am I reading the README in wrong way?

Thanks for the support.

**Comment by faizan80** [comment]
Changing the url to:
flyway.url=jdbc:mysql://127.0.0.1:3306/c360_stg5

woprked better but I have to verify it properly.

**Comment by faizan80** [comment]
and that worked !!!

**Comment by dhoer** [comment]
Fixed the typo in readme.  Sorry about that.
