### ISSUE TITLE
Http endpoint should be changed to Https

### ISSUE THREAD

**Issue by kennethgds** [dhoer/chef-flywaydb#44]
@rackerbenoit 

[Defaults file:](https://github.com/rackerbenoit/chef-flywaydb/blob/master/attributes/default.rb)

These links need to be changed to *https* since *http* is not available anymore

1) `default['flywaydb']['mariadb']['url'] = 'http://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/`

2) `default['flywaydb']['mysql']['url'] = 'http://repo1.maven.org/maven2/mysql/mysql-connector-java/`

**Comment by rackerbenoit** [comment]
Feel free to open a PR for this, or include in the current PR for 6.0.0-beta
