### ISSUE TITLE
Support search for and load configuration files

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-flywaydb#5]
See https://flywaydb.org/documentation/commandline/#configFile for more information.

**Comment by dhoer** [comment]
@krapfl Feel free to offer suggestions on how this functionality could be implemented.

**Comment by dhoer** [comment]
@akrapfl  I propose the following:
`flyway_conf` -  A String containing file path or Hash of settings to copy or write to <install-dir>/conf/flyway.conf.  Settings in conf or ext_conf override settings configured in flyway.conf, and params override all settings. 

The rest would behave the same.  Would that satisfy your requirements?

**Comment by akrapfl** [comment]
Is the hash consistent with the existing `conf` attribute?  If so (and even if not), yes, this sounds like it will work for me.  The only reason for the question is that it makes both fields pretty consistent with each other.  Yeah, let's try it.

**Comment by dhoer** [comment]
Yes, the hash is consistent with how conf works.  I could create an alt_conf that would take a string or hash or an array of strings or hashes to be consistent and deprecate conf and ext_conf.

**Comment by dhoer** [comment]
@akrapfl Initial check-in of flyway.conf rewrite: https://github.com/dhoer/chef-flywaydb/tree/flyway_conf
