### ISSUE TITLE
extracting to flyway-4.0 on windows

### ISSUE THREAD

**Issue by albeekj** [dhoer/chef-flywaydb#9]
Install operation is extracting to "#{ENV['SYSTEMDRIVE']}\\flyway" flyway-4.0 and not straight into flyway directory.  I think it is a change in the executable download for 4.0.  I can just move the files, but I am sure a cleaner way is to modify the conf_dir attribute.

**Comment by dhoer** [comment]
How did you deal with 'The password does not meet the password policy requirements.' on windows platform?  I added the password attribute, but do I really need it?

**Comment by dhoer** [comment]
I will release this branch once I'm confident that the password attribute is needed.

**Comment by albeekj** [comment]
I didn't get a password requirement error, just the extraction issue.  My password is the std strong password 12+ char upper, lower, nums, special char, etc.  Thank you for looking at this so fast.

**Comment by dhoer** [comment]
I will just leave it in. Thanks
